name: Download artifact
on:
  workflow_dispatch:
    inputs:
      run_id:
        required: true
        type: number
jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
    - uses: dawidd6/action-download-artifact@v2
      with:
        repo: wilsonianb/upload-artifact
        github_token: ${{secrets.UPLOAD_ACTION_TOKEN}}
        # run_id: ${{ github.event.inputs.run_id }}
        run_id: ${{ inputs.run_id }}
        name: license
